title: Building Minesweeper with Object-Orientated-Programming
description: >-
  In this course you will learn to build the class game of Minesweeper with
  Python.
template:
  repo: building-minesweeper-with-object-orientated-programming-template
  name: building-minesweeper-with-object-orientated-programming
  description: Building Minesweeper game
before:
  - type: createIssue
    title: Welcome to Building Minesweeper!
    body: new-issue.md
steps:
  - title: Welcome to Minesweper!
    description: >-
      Let's object-oriented programming to build a classic and nostalgic
      Minesweeper game in Python!
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
